import type { Metadata, Viewport } from 'next';
import { Inter, Roboto } from 'next/font/google';

import { Toaster } from '@/components/ui/toast';
import { ThemeProvider } from '@/components/theme-provider';
import { cn } from '@/lib/utils';
import './globals.css';

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-heading',
});
const roboto = Roboto({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const viewport: Viewport = { viewportFit: 'cover' };

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
	return (
		<html
			lang="en"
			className={cn(
				'h-full',
				'antialiased',
				roboto.variable,
				inter.variable,
				'font-sans',
			)}
			suppressHydrationWarning
		>
			<body className="min-h-full flex flex-col">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					{children}

					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	);
}
